/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import java.io.File;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author david
 */
public class AdoptionFormFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdoptionFormFrame
     */
    public AdoptionFormFrame() {
        initComponents();
        populateDailyTimeComboBox();
        populateInterestComboBox();
        populateTestComboBox();
    }
    //check boxes
    private boolean isHouseOwnerSelected = false;
    private boolean isAuthorizationSelected = false;
    private boolean isMotiveSelected = false;
    private boolean isOtherPetSelected = false;
    
    //combo boxes
    private Integer selectedDailyTime = null;
    private Integer selectedInterest = null;
    
    //file chooser
    private File selectedPetSpaceFile = null;
    private File selectedSleepingSpaceFile = null;
    private File selectedPetPhotoFile = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        AFisHouseOwnerCheck = new javax.swing.JCheckBox();
        AFauthorizationCheck = new javax.swing.JCheckBox();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        AFmotiveCheck = new javax.swing.JCheckBox();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        AFdailyTimeCBOX = new javax.swing.JComboBox<>();
        AFinterestCBOX = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        AFpetSpaceFC = new javax.swing.JFileChooser();
        AFsleepingSpaceFC = new javax.swing.JFileChooser();
        AFbudgetJSPIN = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        AFotherPetsCheck = new javax.swing.JCheckBox();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        AFyearsWithPetJSPIN = new javax.swing.JSpinner();
        AFconfirmBTN = new javax.swing.JButton();
        AFpetPhotoFC = new javax.swing.JFileChooser();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        AFreturnHomeBTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        testCBOX = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(203, 125, 188));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adoption form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        AFisHouseOwnerCheck.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        AFisHouseOwnerCheck.setText("Do you own a house?");
        AFisHouseOwnerCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFisHouseOwnerCheckBTNActionPerformed(evt);
            }
        });

        AFauthorizationCheck.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        AFauthorizationCheck.setText("Do you have authorization to have pets where you live?");
        AFauthorizationCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFauthorizationCheckActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel2.setText("Budget destined for the pet per month (en colones)");

        AFmotiveCheck.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        AFmotiveCheck.setText("Is the pet for care?");
        AFmotiveCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFmotiveCheckActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel3.setText("Average daily time the pet would be accompanied (hours)");

        AFdailyTimeCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFdailyTimeCBOXActionPerformed(evt);
            }
        });

        AFinterestCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFinterestCBOXActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel4.setText("Interest in adopting the pet");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel7.setText("Pet space photo");

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel8.setText("Sleeping space photo");

        AFpetSpaceFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFpetSpaceFCActionPerformed(evt);
            }
        });

        AFsleepingSpaceFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFsleepingSpaceFCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AFmotiveCheck)
                            .addComponent(AFisHouseOwnerCheck)
                            .addComponent(AFauthorizationCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(AFbudgetJSPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AFinterestCBOX, javax.swing.GroupLayout.Alignment.LEADING, 0, 78, Short.MAX_VALUE)
                                    .addComponent(AFdailyTimeCBOX, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AFpetSpaceFC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(AFsleepingSpaceFC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(AFisHouseOwnerCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFauthorizationCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AFbudgetJSPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFmotiveCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AFdailyTimeCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AFinterestCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFpetSpaceFC, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFsleepingSpaceFC, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        AFotherPetsCheck.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        AFotherPetsCheck.setText("Do you have any other pets?");
        AFotherPetsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFotherPetsCheckActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel5.setText("Years of the pet living with you");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFotherPetsCheck)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(AFyearsWithPetJSPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AFotherPetsCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AFyearsWithPetJSPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AFconfirmBTN.setBackground(new java.awt.Color(203, 125, 188));
        AFconfirmBTN.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        AFconfirmBTN.setForeground(new java.awt.Color(255, 255, 255));
        AFconfirmBTN.setText("Confirm");
        AFconfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFconfirmBTNActionPerformed(evt);
            }
        });

        AFpetPhotoFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFpetPhotoFCActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel9.setText("Other pet photo");

        AFreturnHomeBTN.setBackground(new java.awt.Color(203, 125, 188));
        AFreturnHomeBTN.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        AFreturnHomeBTN.setForeground(new java.awt.Color(255, 255, 255));
        AFreturnHomeBTN.setText("Return Home");
        AFreturnHomeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFreturnHomeBTNActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(203, 125, 188));

        testCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testCBOXActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select a Pet");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Adoption Test");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AFpetPhotoFC, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AFconfirmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AFreturnHomeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AFpetPhotoFC, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AFconfirmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AFreturnHomeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1051, 957);
    }// </editor-fold>//GEN-END:initComponents
    
    public String getUsername() {
        String fileName = "user.txt"; // Name of the file in your project directory
        String user = null;

        try {
            BufferedReader reader = new BufferedReader(new FileReader(fileName));
            user = reader.readLine(); // Read the first line
            reader.close();
        } catch (IOException e) {
            // Handle any potential IOException here, e.g., show an error message.
            e.printStackTrace();
        }

        return user;
    }
    
    private void populateDailyTimeComboBox(){
        for (int i = 1; i <= 24; i++) {
            AFdailyTimeCBOX.addItem(i + " hours");
        }
    }
    
    private void populateInterestComboBox(){
        for (int i = 1; i <= 10; i++) {
            AFinterestCBOX.addItem(i + "");
        }
    }
    
    // Method to populate the JComboBox
    private void populateTestComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            // Establish a database connection
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");

            // Define your SQL query to retrieve data
            String sql = "SELECT IDPET, PETNAME FROM PET";

            // Prepare and execute the SQL query
            preparedStatement = connection.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();

            // Add the retrieved data to the model
            while (resultSet.next()) {
                String item = resultSet.getString("IDPET"); // Replace with the actual column name
                String petName = resultSet.getString("PETNAME");
                String itemm = item + ", " + petName;
                model.addElement(itemm);
            }

            // Set the model for the JComboBox
            testCBOX.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close database resources
            try {
                if (resultSet != null) resultSet.close();
                if (preparedStatement != null) preparedStatement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void AFisHouseOwnerCheckBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFisHouseOwnerCheckBTNActionPerformed
        isHouseOwnerSelected = AFisHouseOwnerCheck.isSelected();
    }//GEN-LAST:event_AFisHouseOwnerCheckBTNActionPerformed

    private void AFauthorizationCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFauthorizationCheckActionPerformed
        isAuthorizationSelected = AFauthorizationCheck.isSelected();
    }//GEN-LAST:event_AFauthorizationCheckActionPerformed

    private void AFmotiveCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFmotiveCheckActionPerformed
        isMotiveSelected = AFmotiveCheck.isSelected();
    }//GEN-LAST:event_AFmotiveCheckActionPerformed

    private void AFotherPetsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFotherPetsCheckActionPerformed
        isOtherPetSelected = AFotherPetsCheck.isSelected();
    }//GEN-LAST:event_AFotherPetsCheckActionPerformed

    private void AFpetPhotoFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFpetPhotoFCActionPerformed
        // Create and configure a JFileChooser for pet photos
        JFileChooser fileChooser = new JFileChooser();

        // Show the file dialog to the user
        int returnVal = fileChooser.showOpenDialog(this);

        // Check if the user selected a file
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // Get the selected pet photo file
            selectedPetPhotoFile = fileChooser.getSelectedFile();
        } else {
            // The user canceled or closed the dialog
            selectedPetPhotoFile = null;
        }
    }//GEN-LAST:event_AFpetPhotoFCActionPerformed

    private void AFpetSpaceFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFpetSpaceFCActionPerformed
        // Create and configure a JFileChooser
        JFileChooser fileChooser = new JFileChooser();

        // Show the file dialog to the user
        int returnVal = fileChooser.showOpenDialog(this);

        // Check if the user selected a file
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // Get the selected file
            selectedPetSpaceFile = fileChooser.getSelectedFile();
        } else {
            // The user canceled or closed the dialog
            selectedPetSpaceFile = null;
        }
    }//GEN-LAST:event_AFpetSpaceFCActionPerformed

    private void AFsleepingSpaceFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFsleepingSpaceFCActionPerformed
         // Create and configure a JFileChooser for sleeping space
        JFileChooser fileChooser = new JFileChooser();

        // Show the file dialog to the user
        int returnVal = fileChooser.showOpenDialog(this);

        // Check if the user selected a file
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // Get the selected file for sleeping space
            selectedSleepingSpaceFile = fileChooser.getSelectedFile();
        } else {
            // The user canceled or closed the dialog
            selectedSleepingSpaceFile = null;
        }
    }//GEN-LAST:event_AFsleepingSpaceFCActionPerformed

    private void AFconfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFconfirmBTNActionPerformed
        
        //Jspin
        Object petBudget = AFbudgetJSPIN.getValue();
        Object yearsWithPet = AFyearsWithPetJSPIN.getValue();
        
        //is house owner
        if (isHouseOwnerSelected) {
            System.out.println("House owner checkbox is selected");
        }
        
        //authorization
        if (isAuthorizationSelected) {
            System.out.println("Authorization checkbox is selected");
        }
        
        //motive
        if (isMotiveSelected) {
            System.out.println("Motive checkbox is selected");
        }
        
        //average daily time
        if (selectedDailyTime != null) {
            System.out.println("Selected daily time: " + selectedDailyTime);
        } else {
            System.out.println("No daily time option selected");
        }
        
        //interest
            if (selectedInterest != null) {
            System.out.println("Selected interest: " + selectedInterest);
        } else {
            System.out.println("No interest option selected");
        }
            
        //authorization
        if (isOtherPetSelected) {
            System.out.println("Other pet checkbox is selected");
        }
        
        // pet space photo
        if (selectedPetSpaceFile != null) {
            // You can now use the selectedFile in your code
            String filePath = selectedPetSpaceFile.getAbsolutePath();
            System.out.println("Selected file: " + filePath);
        } else {
            System.out.println("No file selected.");
        }
        
        //pet sleeping space photo
        if (selectedSleepingSpaceFile != null) {
            // You can now use the selectedSleepingSpaceFile in your code
            String filePath = selectedSleepingSpaceFile.getAbsolutePath();
            System.out.println("Selected sleeping space file: " + filePath);
        } else {
            System.out.println("No sleeping space file selected.");
        }
        
        //old pet photo
        if (selectedPetPhotoFile != null) {
            // You can now use the selectedPetPhotoFile in your code
            String filePath = selectedPetPhotoFile.getAbsolutePath();
            System.out.println("Selected pet photo file: " + filePath);
        } else {
            System.out.println("No pet photo file selected.");
        }
        // adoption test
        String test = testCBOX.getSelectedItem().toString();
        //Interest
        String interest = AFinterestCBOX.getSelectedItem().toString();
        
        String username = getUsername();
        

        
        
        this.dispose();
    }//GEN-LAST:event_AFconfirmBTNActionPerformed

    private void AFreturnHomeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFreturnHomeBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_AFreturnHomeBTNActionPerformed

    private void testCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testCBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testCBOXActionPerformed

    private void AFinterestCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFinterestCBOXActionPerformed
        // Store the selected interest option as an integer
        
    }//GEN-LAST:event_AFinterestCBOXActionPerformed

    private void AFdailyTimeCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFdailyTimeCBOXActionPerformed
        
    }//GEN-LAST:event_AFdailyTimeCBOXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdoptionFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdoptionFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdoptionFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdoptionFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdoptionFormFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AFauthorizationCheck;
    private javax.swing.JSpinner AFbudgetJSPIN;
    private javax.swing.JButton AFconfirmBTN;
    private javax.swing.JComboBox<String> AFdailyTimeCBOX;
    private javax.swing.JComboBox<String> AFinterestCBOX;
    private javax.swing.JCheckBox AFisHouseOwnerCheck;
    private javax.swing.JCheckBox AFmotiveCheck;
    private javax.swing.JCheckBox AFotherPetsCheck;
    private javax.swing.JFileChooser AFpetPhotoFC;
    private javax.swing.JFileChooser AFpetSpaceFC;
    private javax.swing.JButton AFreturnHomeBTN;
    private javax.swing.JFileChooser AFsleepingSpaceFC;
    private javax.swing.JSpinner AFyearsWithPetJSPIN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> testCBOX;
    // End of variables declaration//GEN-END:variables
}
