/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import oracle.jdbc.OracleTypes;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.util.Base64;
/**
 *
 * @author david
 */
public class MainDisplay extends javax.swing.JFrame {

    /**
     * Creates new form MainDisplay
     */
    public MainDisplay(){
        cleanUserFile();
        initComponents();
        
    }
    
    
    private String loginUsername;
    private String loginRescuer;
    private String adopterPassword;
    private String rescuerPassword;

    // Getter and Setter for loginUsername
    public String getLoginUsername() {
        return loginUsername;
    }

    public void setLoginUsername(String loginUsername) {
        this.loginUsername = loginUsername;
    }

    // Getter and Setter for loginRescuer
    public String getLoginRescuer() {
        return loginRescuer;
    }

    public void setLoginRescuer(String loginRescuer) {
        this.loginRescuer = loginRescuer;
    }

    // Getter and Setter for adopterPassword
    public String getAdopterPassword() {
        return adopterPassword;
    }

    public void setAdopterPassword(String adopterPassword) {
        this.adopterPassword = adopterPassword;
    }

    // Getter and Setter for rescuerPassword
    public String getRescuerPassword() {
        return rescuerPassword;
    }

    public void setRescuerPassword(String rescuerPassword) {
        this.rescuerPassword = rescuerPassword;
    }
    public void cleanUserFile() {
        String fileName = "user.txt"; 

        try {
            FileWriter writer = new FileWriter(fileName, false); 
            writer.write(""); 
            writer.close();
        } catch (IOException e) {
            
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel imgBackgroundd = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel userLoginLabel = new javax.swing.JLabel();
        loginUsernameTF = new javax.swing.JTextField();
        adopterLoginBTN = new javax.swing.JButton();
        passwordIconLabel = new javax.swing.JLabel();
        usernameIconLabel = new javax.swing.JLabel();
        javax.swing.JLabel rescuerLoginLabel = new javax.swing.JLabel();
        loginRescuerTF = new javax.swing.JTextField();
        rescuerLoginBTN = new javax.swing.JButton();
        createAccBTN = new javax.swing.JButton();
        adopterPasswordTF = new javax.swing.JPasswordField();
        rescuerPasswordTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 234, 214));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(619, 412));
        jPanel2.setMinimumSize(new java.awt.Dimension(619, 412));
        jPanel2.setPreferredSize(new java.awt.Dimension(619, 412));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(201, 152, 114));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(182, 107, 41));
        jLabel2.setText("Welcome to Dog Lovers");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 290, 46));

        imgBackgroundd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto1/Golden Retriever dogggg.jpg"))); // NOI18N
        jPanel2.add(imgBackgroundd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        jPanel3.setBackground(new java.awt.Color(247, 234, 214));

        userLoginLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        userLoginLabel.setForeground(new java.awt.Color(220, 161, 121));
        userLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLoginLabel.setText("ADOPTER LOGIN");

        loginUsernameTF.setBackground(new java.awt.Color(201, 152, 114));
        loginUsernameTF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        loginUsernameTF.setForeground(new java.awt.Color(255, 255, 255));
        loginUsernameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginUsernameTF.setText("Username");
        loginUsernameTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginUsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTFActionPerformed(evt);
            }
        });

        adopterLoginBTN.setBackground(new java.awt.Color(201, 152, 114));
        adopterLoginBTN.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        adopterLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        adopterLoginBTN.setText("LOGIN");
        adopterLoginBTN.setBorderPainted(false);
        adopterLoginBTN.setPreferredSize(new java.awt.Dimension(166, 33));
        adopterLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adopterLoginBTNActionPerformed(evt);
            }
        });

        passwordIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        usernameIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rescuerLoginLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        rescuerLoginLabel.setForeground(new java.awt.Color(220, 161, 121));
        rescuerLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescuerLoginLabel.setText("RESCUER LOGIN");

        loginRescuerTF.setBackground(new java.awt.Color(201, 152, 114));
        loginRescuerTF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        loginRescuerTF.setForeground(new java.awt.Color(255, 255, 255));
        loginRescuerTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginRescuerTF.setText("Username");
        loginRescuerTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginRescuerTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRescuerTFActionPerformed(evt);
            }
        });

        rescuerLoginBTN.setBackground(new java.awt.Color(201, 152, 114));
        rescuerLoginBTN.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        rescuerLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        rescuerLoginBTN.setText("LOGIN");
        rescuerLoginBTN.setBorderPainted(false);
        rescuerLoginBTN.setPreferredSize(new java.awt.Dimension(166, 33));
        rescuerLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescuerLoginBTNActionPerformed(evt);
            }
        });

        createAccBTN.setBackground(new java.awt.Color(201, 152, 114));
        createAccBTN.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        createAccBTN.setForeground(new java.awt.Color(255, 255, 255));
        createAccBTN.setText("Create account");
        createAccBTN.setBorderPainted(false);
        createAccBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBTNActionPerformed(evt);
            }
        });

        adopterPasswordTF.setBackground(new java.awt.Color(201, 152, 114));
        adopterPasswordTF.setText("jPasswordField1");
        adopterPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adopterPasswordTFActionPerformed(evt);
            }
        });

        rescuerPasswordTF.setBackground(new java.awt.Color(201, 152, 114));
        rescuerPasswordTF.setText("jPasswordField1");
        rescuerPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescuerPasswordTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(userLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(adopterPasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                            .addComponent(loginUsernameTF))))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rescuerLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loginRescuerTF, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(rescuerPasswordTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(adopterLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rescuerLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordIconLabel)
                            .addComponent(usernameIconLabel)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(createAccBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLoginLabel)
                    .addComponent(rescuerLoginLabel))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(loginUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginRescuerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adopterPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rescuerPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adopterLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rescuerLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(passwordIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(createAccBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adopterLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adopterLoginBTNActionPerformed
        String userUsername = loginUsernameTF.getText(); // Get the text from the username text field
        String userPassword = adopterPasswordTF.getText(); // Get the text from the password text field
        Connection connection = null;
        CallableStatement callableStatement = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        String RPassword ;
        
        try {
            String filePath = "user.txt"; // The path to your file in the NetBeans project
            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath));
            writer.write(userUsername);
            writer.close();
            //db
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");
            String sql = "{ ? = call getIdPersonPerUsernames(?) }";
            callableStatement = connection.prepareCall(sql);
            callableStatement.registerOutParameter(1, Types.INTEGER);  // Tipo de datos de retorno de la función
            callableStatement.setString(2, userUsername);
            
            callableStatement.execute();
            int result = callableStatement.getInt(1); // 1 es el índice del parámetro de salida
            
            // Utilizar el resultado como desees
            System.out.println("Resultado de la función: " + result);
            callableStatement.close();
            String sql2 = "{ ? = call getIdPasswordPerUsernames(?) }";
            callableStatement = connection.prepareCall(sql2);
            callableStatement.registerOutParameter(1, Types.VARCHAR);  // Tipo de datos de retorno de la función
            callableStatement.setString(2, userUsername);
            callableStatement.execute();
            RPassword = callableStatement.getString(1); 
            callableStatement.close();
            connection.close();
            
            if(result>0 && RPassword!=""){ 
                UsersFrame usersFrame = new UsersFrame();
                usersFrame.setVisible(true);
                this.dispose(); 
            }else{
                JOptionPane.showMessageDialog(null, "Username not registered or incorrect password", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (IOException e) {
            // Handle any potential IOException here, e.g., show an error message.
            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(MainDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Create and open the UsersFrame
        //UsersFrame usersFrame = new UsersFrame();
        //usersFrame.setVisible(true);
        
    }//GEN-LAST:event_adopterLoginBTNActionPerformed

    private void loginUsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTFActionPerformed

    private void loginRescuerTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRescuerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginRescuerTFActionPerformed

    private void rescuerLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescuerLoginBTNActionPerformed
        String rescuerUsername = loginRescuerTF.getText(); // Get the text from the rescuer text field
        String rescuerPassword = rescuerPasswordTF.getText(); // Get the text from the password text field
        Connection connection = null;
        CallableStatement callableStatement = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        String RPassword ;
        
        try {
            String filePath = "user.txt"; // The path to your file in the NetBeans project
            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath));
            writer.write(rescuerUsername);
            writer.close();
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:BDPRUEBA", "ge", "ge");
            String sql = "{ ? = call getIdPersonPerUsernames(?) }";
            callableStatement = connection.prepareCall(sql);
            callableStatement.registerOutParameter(1, Types.INTEGER);  // Tipo de datos de retorno de la función
            callableStatement.setString(2, rescuerUsername);

            callableStatement.execute();
            int result = callableStatement.getInt(1);  // 1 es el índice del parámetro de salida
             
            // Utilizar el resultado como desees
            System.out.println("Resultado de la función: " + result);
            callableStatement.close();
            String sql2 = "{ ? = call getIdPasswordPerUsernames(?) }";
            callableStatement = connection.prepareCall(sql2);
            callableStatement.registerOutParameter(1, Types.VARCHAR);  // Tipo de datos de retorno de la función
            callableStatement.setString(2, rescuerUsername);
            callableStatement.execute();
            RPassword = callableStatement.getString(1); 
            callableStatement.close();
            connection.close();
            if(result>0 && RPassword!=""){ 
                UsersFrame usersFrame = new UsersFrame();
                usersFrame.setVisible(true);
                this.dispose(); 
            }else{
                JOptionPane.showMessageDialog(null, "Username not registered or incorrect password", "Error", JOptionPane.ERROR_MESSAGE);    
            }
        } catch (IOException e) {
            // Handle any potential IOException here, e.g., show an error message.
            e.printStackTrace();
        } catch (SQLException ex) {
           Logger.getLogger(MainDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Create and open the UsersFrame
        //RescuerHome rescuerHome = new RescuerHome();
        //rescuerHome.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_rescuerLoginBTNActionPerformed

    private void createAccBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBTNActionPerformed
        // Create an instance of the RegisterFrame and make it visible
        RegisterFrame registerFrame = new RegisterFrame();
        registerFrame.setVisible(true);

        // Close the current frame (optional)
        this.dispose();
    }//GEN-LAST:event_createAccBTNActionPerformed

    private void adopterPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adopterPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adopterPasswordTFActionPerformed

    private void rescuerPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescuerPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rescuerPasswordTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adopterLoginBTN;
    private javax.swing.JPasswordField adopterPasswordTF;
    private javax.swing.JButton createAccBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField loginRescuerTF;
    private javax.swing.JTextField loginUsernameTF;
    private javax.swing.JLabel passwordIconLabel;
    private javax.swing.JButton rescuerLoginBTN;
    private javax.swing.JPasswordField rescuerPasswordTF;
    private javax.swing.JLabel usernameIconLabel;
    // End of variables declaration//GEN-END:variables
}
