/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import Connect.ConexionOracle;
import java.text.SimpleDateFormat;
import java.util.Date;

//
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.Types;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel; 
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import oracle.jdbc.OracleTypes;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


/**
 *
 * @author david
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        populateCountryComboBox();
        populateProvinceComboBox();
        populateGenreComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPanel = new javax.swing.JPanel();
        javax.swing.JPanel registerInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea1 = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea3 = new javax.swing.JTextArea();
        registerLabelPanel = new javax.swing.JPanel();
        javax.swing.JLabel registrationLabel = new javax.swing.JLabel();
        dogIcon = new javax.swing.JLabel();
        javax.swing.JPanel registerTFPanel = new javax.swing.JPanel();
        rFirstNameTF = new javax.swing.JTextField();
        rSecondNameTF = new javax.swing.JTextField();
        rFirstSurnameTF = new javax.swing.JTextField();
        rSecondSurnameTF = new javax.swing.JTextField();
        javax.swing.JLabel rFirstNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel rSecondNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel rFirstSurnameLabel = new javax.swing.JLabel();
        javax.swing.JLabel rSecondSurnameLabel = new javax.swing.JLabel();
        rEmailTF = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        rPhoneNumberTF = new javax.swing.JTextField();
        rBirthdateJC = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        rCountriesUserPanel = new javax.swing.JPanel();
        rCountryCBOX = new javax.swing.JComboBox<>();
        javax.swing.JLabel rCountryLabel = new javax.swing.JLabel();
        javax.swing.JLabel rProvinceLabel = new javax.swing.JLabel();
        javax.swing.JLabel rCantonLabel = new javax.swing.JLabel();
        javax.swing.JLabel rDistrictLabel = new javax.swing.JLabel();
        javax.swing.JLabel rUsernameLabel = new javax.swing.JLabel();
        rUsernameTF = new javax.swing.JTextField();
        javax.swing.JLabel rUsernameLabel1 = new javax.swing.JLabel();
        rPasswordTF = new javax.swing.JTextField();
        rProvinceCBOX = new javax.swing.JComboBox<>();
        rCantonCBOX = new javax.swing.JComboBox<>();
        rDistrictCBOX = new javax.swing.JComboBox<>();
        javax.swing.JLabel rDistrictLabel1 = new javax.swing.JLabel();
        rIdTF = new javax.swing.JTextField();
        javax.swing.JLabel rProvinceLabel1 = new javax.swing.JLabel();
        rGenreCBOX = new javax.swing.JComboBox<>();
        rAdopterBtn = new javax.swing.JButton();
        rRescuerBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        rRescueCenterNameTF = new javax.swing.JTextField();
        returnHomeBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        registerPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        registerPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        registerPanel.setRequestFocusEnabled(false);

        registerInfoPanel.setBackground(new java.awt.Color(107, 181, 128));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Welcome to Our Pet Adoption Center!");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Why Adopt?");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(107, 181, 128));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("-Give a homeless pet a second chance \nat a happy life.\n-Experience the unconditional love and joy\n that a pet brings.\n-Be a part of a compassionate community\n that values animal welfare.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Your Journey Begins Here");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(107, 181, 128));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Thank you for choosing to make a difference in a \n furry friend's life by considering adoption. We are\nthrilled to have you here at our Pet Adoption Center.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea2);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(107, 181, 128));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("By registering, you are taking the first step towards\nmaking  a significant impact on a pet's life. Our\nregistration process is quick and easy. . Here's what\n you can expect:\n\n1- Create Your Profile:\n\n2- Preferences:\n\n3- Browse Our Pets: \n\n4- Meet Your Match:\n\n5- Adoption Process: \n\n\n\n");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout registerInfoPanelLayout = new javax.swing.GroupLayout(registerInfoPanel);
        registerInfoPanel.setLayout(registerInfoPanelLayout);
        registerInfoPanelLayout.setHorizontalGroup(
            registerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        registerInfoPanelLayout.setVerticalGroup(
            registerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerInfoPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4))
        );

        registerLabelPanel.setBackground(new java.awt.Color(107, 181, 128));

        registrationLabel.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        registrationLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationLabel.setText("Registration Page");

        javax.swing.GroupLayout registerLabelPanelLayout = new javax.swing.GroupLayout(registerLabelPanel);
        registerLabelPanel.setLayout(registerLabelPanelLayout);
        registerLabelPanelLayout.setHorizontalGroup(
            registerLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        registerLabelPanelLayout.setVerticalGroup(
            registerLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLabelPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(registrationLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        registerTFPanel.setBackground(new java.awt.Color(255, 255, 255));

        rFirstNameTF.setOpaque(true);
        rFirstNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFirstNameTFActionPerformed(evt);
            }
        });

        rSecondNameTF.setOpaque(true);
        rSecondNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSecondNameTFActionPerformed(evt);
            }
        });

        rFirstSurnameTF.setOpaque(true);
        rFirstSurnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFirstSurnameTFActionPerformed(evt);
            }
        });

        rSecondSurnameTF.setOpaque(true);
        rSecondSurnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSecondSurnameTFActionPerformed(evt);
            }
        });

        rFirstNameLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rFirstNameLabel.setForeground(new java.awt.Color(107, 181, 128));
        rFirstNameLabel.setText("First name");

        rSecondNameLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rSecondNameLabel.setForeground(new java.awt.Color(107, 181, 128));
        rSecondNameLabel.setText("Second name");

        rFirstSurnameLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rFirstSurnameLabel.setForeground(new java.awt.Color(107, 181, 128));
        rFirstSurnameLabel.setText("First surname");

        rSecondSurnameLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rSecondSurnameLabel.setForeground(new java.awt.Color(107, 181, 128));
        rSecondSurnameLabel.setText("Second surname");

        rEmailTF.setOpaque(true);
        rEmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEmailTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 181, 128));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 181, 128));
        jLabel5.setText("Phone number");

        rPhoneNumberTF.setOpaque(true);
        rPhoneNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPhoneNumberTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 181, 128));
        jLabel6.setText("Birthdate");

        rCountriesUserPanel.setBackground(new java.awt.Color(255, 255, 255));

        rCountryCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCountryCBOXActionPerformed(evt);
            }
        });

        rCountryLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rCountryLabel.setForeground(new java.awt.Color(107, 181, 128));
        rCountryLabel.setText("Country");

        rProvinceLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rProvinceLabel.setForeground(new java.awt.Color(107, 181, 128));
        rProvinceLabel.setText("Province");

        rCantonLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rCantonLabel.setForeground(new java.awt.Color(107, 181, 128));
        rCantonLabel.setText("Canton");

        rDistrictLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rDistrictLabel.setForeground(new java.awt.Color(107, 181, 128));
        rDistrictLabel.setText("District");

        rUsernameLabel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rUsernameLabel.setForeground(new java.awt.Color(107, 181, 128));
        rUsernameLabel.setText("Username");

        rUsernameTF.setOpaque(true);
        rUsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUsernameTFActionPerformed(evt);
            }
        });

        rUsernameLabel1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rUsernameLabel1.setForeground(new java.awt.Color(107, 181, 128));
        rUsernameLabel1.setText("Password");

        rPasswordTF.setOpaque(true);
        rPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPasswordTFActionPerformed(evt);
            }
        });

        rProvinceCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rProvinceCBOXActionPerformed(evt);
            }
        });

        rCantonCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCantonCBOXActionPerformed(evt);
            }
        });

        rDistrictCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDistrictCBOXActionPerformed(evt);
            }
        });

        rDistrictLabel1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rDistrictLabel1.setForeground(new java.awt.Color(107, 181, 128));
        rDistrictLabel1.setText("Identification");

        rIdTF.setOpaque(true);
        rIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rIdTFActionPerformed(evt);
            }
        });

        rProvinceLabel1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        rProvinceLabel1.setForeground(new java.awt.Color(107, 181, 128));
        rProvinceLabel1.setText("Genre");

        rGenreCBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rGenreCBOXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rCountriesUserPanelLayout = new javax.swing.GroupLayout(rCountriesUserPanel);
        rCountriesUserPanel.setLayout(rCountriesUserPanelLayout);
        rCountriesUserPanelLayout.setHorizontalGroup(
            rCountriesUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rCountriesUserPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(rCountriesUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rProvinceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rDistrictLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rDistrictLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rProvinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rCountryCBOX, 0, 199, Short.MAX_VALUE)
                    .addComponent(rCantonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUsernameTF)
                    .addComponent(rPasswordTF)
                    .addComponent(rProvinceCBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rCantonCBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rDistrictCBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rIdTF)
                    .addComponent(rGenreCBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        rCountriesUserPanelLayout.setVerticalGroup(
            rCountriesUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rCountriesUserPanelLayout.createSequentialGroup()
                .addComponent(rCountryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rCountryCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rProvinceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rProvinceCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rCantonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rCantonCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rDistrictLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rDistrictCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rUsernameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rDistrictLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rProvinceLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rGenreCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        rAdopterBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        rAdopterBtn.setForeground(new java.awt.Color(107, 181, 128));
        rAdopterBtn.setText("Create as adopter");
        rAdopterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAdopterBtnActionPerformed(evt);
            }
        });

        rRescuerBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        rRescuerBtn.setForeground(new java.awt.Color(107, 181, 128));
        rRescuerBtn.setText("Create as rescuer");
        rRescuerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rRescuerBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(107, 181, 128));
        jButton1.setText("Create as Rescue Center");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(107, 181, 128));
        jLabel7.setText("Rescue Center name");

        rRescueCenterNameTF.setOpaque(true);
        rRescueCenterNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rRescueCenterNameTFActionPerformed(evt);
            }
        });

        returnHomeBTN.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        returnHomeBTN.setForeground(new java.awt.Color(107, 181, 128));
        returnHomeBTN.setText("Return home");
        returnHomeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerTFPanelLayout = new javax.swing.GroupLayout(registerTFPanel);
        registerTFPanel.setLayout(registerTFPanelLayout);
        registerTFPanelLayout.setHorizontalGroup(
            registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerTFPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerTFPanelLayout.createSequentialGroup()
                        .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerTFPanelLayout.createSequentialGroup()
                                .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rBirthdateJC, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                                    .addComponent(rRescueCenterNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rAdopterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rRescuerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(returnHomeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))))
                            .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rFirstNameTF)
                                .addComponent(rFirstSurnameTF)
                                .addComponent(rSecondSurnameTF)
                                .addComponent(rSecondSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(rFirstSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSecondNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rPhoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSecondNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerTFPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rCountriesUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        registerTFPanelLayout.setVerticalGroup(
            registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerTFPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(rFirstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rFirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSecondNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSecondNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(rFirstSurnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rFirstSurnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSecondSurnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSecondSurnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rPhoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerTFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerTFPanelLayout.createSequentialGroup()
                        .addComponent(rBirthdateJC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(rRescueCenterNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(registerTFPanelLayout.createSequentialGroup()
                        .addComponent(rRescuerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(rAdopterBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(returnHomeBTN))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerTFPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rCountriesUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dogIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 757, Short.MAX_VALUE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registerTFPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addComponent(registerLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerTFPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dogIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getUsername() {
        String fileName = "user.txt"; // Name of the file in your project directory
        String user = null;

        try {
            BufferedReader reader = new BufferedReader(new FileReader(fileName));
            user = reader.readLine(); // Read the first line
            reader.close();
        } catch (IOException e) {
            // Handle any potential IOException here, e.g., show an error message.
            e.printStackTrace();
        }

        return user;
    }
    // Method to populate the JComboBox
    private void populateCountryComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            // Establish a database connection
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");

            // Define your SQL query to retrieve data
            String sql = "SELECT COUNTRYNAME FROM COUNTRY";

            // Prepare and execute the SQL query
            preparedStatement = connection.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();

            // Add the retrieved data to the model
            while (resultSet.next()) {
                String item = resultSet.getString("COUNTRYNAME"); // Replace with the actual column name
                model.addElement(item);
            }

            // Set the model for the JComboBox
            rCountryCBOX.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close database resources
            try {
                if (resultSet != null) resultSet.close();
                if (preparedStatement != null) preparedStatement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void populateProvinceComboBox(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            // Establish a database connection
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");

            // Define your SQL query to retrieve data
            String sql = "SELECT PROVINCENAME FROM PROVINCE";

            // Prepare and execute the SQL query
            preparedStatement = connection.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();

            // Add the retrieved data to the model
            while (resultSet.next()) {
                String item = resultSet.getString("PROVINCENAME"); // Replace with the actual column name
                model.addElement(item);
            }

            // Set the model for the JComboBox
            rProvinceCBOX.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close database resources
            try {
                if (resultSet != null) resultSet.close();
                if (preparedStatement != null) preparedStatement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
         
        private void populateCantonComboBox(String country, String province) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Connection connection = null;
        CallableStatement callableStatement = null;
        ResultSet resultSet = null;

        try {
            // Establish a database connection
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");

            // Call the stored procedure
            callableStatement = connection.prepareCall("{call getCanton(?, ?, ?)}");
            callableStatement.setString(1, country);
            callableStatement.setString(2, province);
            callableStatement.registerOutParameter(3, OracleTypes.CURSOR);
            callableStatement.execute();

            // Get the result set
            resultSet = (ResultSet) callableStatement.getObject(3);

            // Add the retrieved data to the model
            while (resultSet.next()) {
                String item = resultSet.getString("cantonname");
                model.addElement(item);
            }

            // Set the model for the JComboBox
            rCantonCBOX.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close database resources
            try {
                if (resultSet != null) resultSet.close();
                if (callableStatement != null) callableStatement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
        
    private void populateDistrictComboBox(String country, String province, String canton) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Connection connection = null;
        CallableStatement callableStatement = null;
        ResultSet resultSet = null;

        try {
            // Establish a database connection
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");

            // Call the stored procedure to retrieve the Districts
            callableStatement = connection.prepareCall("{call getDistrict(?, ?, ?, ?)}");
            callableStatement.setString(1, country);
            callableStatement.setString(2, province);
            callableStatement.setString(3, canton);
            callableStatement.registerOutParameter(4, OracleTypes.CURSOR);
            callableStatement.execute();

            // Get the result set
            resultSet = (ResultSet) callableStatement.getObject(4);

            // Add the retrieved data to the model
            while (resultSet.next()) {
                String item = resultSet.getString("districtname");
                model.addElement(item);
            }

            // Set the model for the JComboBox
            rDistrictCBOX.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close database resources
            try {
                if (resultSet != null) resultSet.close();
                if (callableStatement != null) callableStatement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    // Method to populate the JComboBox
    private void populateGenreComboBox() {
        // Assuming your ComboBox is named comboBoxGenre
        rGenreCBOX.addItem("Femenino");
        rGenreCBOX.addItem("Masculino");
    }
    
    private void rFirstNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFirstNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rFirstNameTFActionPerformed

    private void rSecondNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSecondNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSecondNameTFActionPerformed

    private void rFirstSurnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFirstSurnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rFirstSurnameTFActionPerformed

    private void rSecondSurnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSecondSurnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSecondSurnameTFActionPerformed

    private void rEmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rEmailTFActionPerformed

    private void rPhoneNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPhoneNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPhoneNumberTFActionPerformed

    private void rCountryCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCountryCBOXActionPerformed
        
    }//GEN-LAST:event_rCountryCBOXActionPerformed

    private void rUsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rUsernameTFActionPerformed

    private void rPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPasswordTFActionPerformed

    private void rAdopterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAdopterBtnActionPerformed
        //text fields
        String firstName = rFirstNameTF.getText();
        String secondName = rSecondNameTF.getText();
        String firstSurname = rFirstSurnameTF.getText();
        String secondSurname = rSecondSurnameTF.getText();
        String email = rEmailTF.getText();
        String phoneNumber = rPhoneNumberTF.getText();
        String username = rUsernameTF.getText();
        String password = rPasswordTF.getText();
        String identification = rIdTF.getText();
        String rescueCenter = rRescueCenterNameTF.getText();
        
        
        //JCalendar
        //Birthdate
        Date selectedBirthdate = rBirthdateJC.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        String formattedBirthdate = dateFormat.format(selectedBirthdate);
        System.out.println("Selected Lost Date: " + formattedBirthdate);
        
        //combo boxes
        String country = rCountryCBOX.getSelectedItem().toString();
        String province = rProvinceCBOX.getSelectedItem().toString();
        String canton = rCantonCBOX.getSelectedItem().toString();
        String district = rDistrictCBOX.getSelectedItem().toString();
        String genre = rGenreCBOX.getSelectedItem().toString();
        
        
        
        try {
            // Create a database connection
            Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");

            connection.setAutoCommit(false);
            // Prepare the SQL statement with placeholders for your procedure parameters
            String callStmt = "{call insertPersonAdoptant(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}";
            CallableStatement callableStatement = connection.prepareCall(callStmt);

            // Set the values for the procedure parameters
            callableStatement.setString(1, firstName);
            callableStatement.setString(2, secondName);
            callableStatement.setString(3, firstSurname);
            callableStatement.setString(4, secondSurname);
            callableStatement.setDate(5, new java.sql.Date(selectedBirthdate.getTime()));
            callableStatement.setString(6, genre);
            callableStatement.setString(7, identification);
            callableStatement.setString(8, username);
            callableStatement.setString(9, password);
            callableStatement.setString(10, email);
            callableStatement.setString(11, phoneNumber);
            callableStatement.setString(12, country);
            callableStatement.setString(13, province);
            callableStatement.setString(14, canton);
            callableStatement.setString(15, district);
            callableStatement.setString(16, rescueCenter);

            // Execute the stored procedure
            callableStatement.execute();

            // Commit the transaction
            connection.commit();
            System.out.println("done");
            // Close the CallableStatement and the Connection
            callableStatement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace(); // Handle any exceptions here
        }
        
        

        
        MainDisplay mainDisplay = new MainDisplay();
        mainDisplay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rAdopterBtnActionPerformed


    private void rRescueCenterNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rRescueCenterNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rRescueCenterNameTFActionPerformed

    private void rProvinceCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rProvinceCBOXActionPerformed
        String selectedCountry = rCountryCBOX.getSelectedItem().toString(); // Replace with the selected country
        String selectedProvince = rProvinceCBOX.getSelectedItem().toString(); // Get the selected Province name

        // Call the stored procedure to retrieve the Cantons
        populateCantonComboBox(selectedCountry, selectedProvince);
    }//GEN-LAST:event_rProvinceCBOXActionPerformed

    private void rCantonCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCantonCBOXActionPerformed
        // Get the selected Country, Province, and Canton
        String selectedCountry = rCountryCBOX.getSelectedItem().toString();// Replace with the selected country
        String selectedProvince = rProvinceCBOX.getSelectedItem().toString();
        String selectedCanton = rCantonCBOX.getSelectedItem().toString(); // Assuming you have a Canton ComboBox

        // Call the stored procedure to populate the District ComboBox
        populateDistrictComboBox(selectedCountry, selectedProvince, selectedCanton);
    }//GEN-LAST:event_rCantonCBOXActionPerformed

    private void rDistrictCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDistrictCBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rDistrictCBOXActionPerformed

    private void rRescuerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rRescuerBtnActionPerformed
        //text fields
        String firstNameR = rFirstNameTF.getText();
        String secondNameR = rSecondNameTF.getText();
        String firstSurnameR = rFirstSurnameTF.getText();
        String secondSurnameR = rSecondSurnameTF.getText();
        String emailR = rEmailTF.getText();
        String phoneNumberR = rPhoneNumberTF.getText();
        String usernameR = rUsernameTF.getText();
        String passwordR = rPasswordTF.getText();
        String identificationR = rIdTF.getText();
        String rescueCenterR = rRescueCenterNameTF.getText();
        
        //JCalendar
        //Birthdate
        Date selectedBirthdateR = rBirthdateJC.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        String formattedBirthdateR = dateFormat.format(selectedBirthdateR);
        System.out.println("Selected Lost Date: " + formattedBirthdateR);
        
        //combo boxes
        String countryR = rCountryCBOX.getSelectedItem().toString();
        String provinceR = rProvinceCBOX.getSelectedItem().toString();
        String cantonR = rCantonCBOX.getSelectedItem().toString();
        String districtR = rDistrictCBOX.getSelectedItem().toString();
        String genreR = rGenreCBOX.getSelectedItem().toString();
        
        
        try {
            // Create a database connection
            Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:DBDAVID", "ge", "ge");

            connection.setAutoCommit(false);
            // Prepare the SQL statement with placeholders for your procedure parameters
            String callStmt = "{call insertPersonRescuer(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}";
            CallableStatement callableStatement = connection.prepareCall(callStmt);

            // Set the values for the procedure parameters
            callableStatement.setString(1, firstNameR);
            callableStatement.setString(2, secondNameR);
            callableStatement.setString(3, firstSurnameR);
            callableStatement.setString(4, secondSurnameR);
            callableStatement.setDate(5, new java.sql.Date(selectedBirthdateR.getTime()));
            callableStatement.setString(6, genreR);
            callableStatement.setString(7, identificationR);
            callableStatement.setString(8, usernameR);
            callableStatement.setString(9, passwordR);
            callableStatement.setString(10, emailR);
            callableStatement.setString(11, phoneNumberR);
            callableStatement.setString(12, countryR);
            callableStatement.setString(13, provinceR);
            callableStatement.setString(14, cantonR);
            callableStatement.setString(15, districtR);
            callableStatement.setString(16, rescueCenterR);

            // Execute the stored procedure
            callableStatement.execute();

            // Commit the transaction
            connection.commit();
            System.out.println("done");
            // Close the CallableStatement and the Connection
            callableStatement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace(); // Handle any exceptions here
        }
        
        
        MainDisplay mainDisplay = new MainDisplay();
        mainDisplay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rRescuerBtnActionPerformed

    private void returnHomeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeBTNActionPerformed
        MainDisplay mainDisplay = new MainDisplay();
        mainDisplay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnHomeBTNActionPerformed

    private void rIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rIdTFActionPerformed

    private void rGenreCBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rGenreCBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rGenreCBOXActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dogIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton rAdopterBtn;
    private com.toedter.calendar.JDateChooser rBirthdateJC;
    private javax.swing.JComboBox<String> rCantonCBOX;
    private javax.swing.JPanel rCountriesUserPanel;
    private javax.swing.JComboBox<String> rCountryCBOX;
    private javax.swing.JComboBox<String> rDistrictCBOX;
    private javax.swing.JTextField rEmailTF;
    private javax.swing.JTextField rFirstNameTF;
    private javax.swing.JTextField rFirstSurnameTF;
    private javax.swing.JComboBox<String> rGenreCBOX;
    private javax.swing.JTextField rIdTF;
    private javax.swing.JTextField rPasswordTF;
    private javax.swing.JTextField rPhoneNumberTF;
    private javax.swing.JComboBox<String> rProvinceCBOX;
    private javax.swing.JTextField rRescueCenterNameTF;
    private javax.swing.JButton rRescuerBtn;
    private javax.swing.JTextField rSecondNameTF;
    private javax.swing.JTextField rSecondSurnameTF;
    private javax.swing.JTextField rUsernameTF;
    private javax.swing.JPanel registerLabelPanel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton returnHomeBTN;
    // End of variables declaration//GEN-END:variables
}
